# Generated by Django 3.2.5 on 2021-08-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationaldays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='day',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
