# Generated by Django 3.2.5 on 2021-08-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationaldays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='day_history',
            field=models.TextField(null=True),
        ),
    ]
