# Generated by Django 3.2.5 on 2021-08-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationaldays', '0002_auto_20210821_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
