# Generated by Django 3.2.5 on 2021-08-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationaldays', '0003_alter_day_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day',
        ),
        migrations.RemoveField(
            model_name='day',
            name='month',
        ),
        migrations.RemoveField(
            model_name='day',
            name='year',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
